import * as express from "express";
import { AdminRouter } from "./admin/admin";
import { AuthRouter } from "./auth";
import { PaymentRouter } from "./payment";
import { TwilioRouter } from "./twilio";
import { Middleware } from "../middleware/auth";
import { EmailRouter } from "./email";
import { ChatRouter } from "./chat";
import { FileRouter } from "./file";
import { ReviewRouter } from "./review";
import { UserRouter } from "./user";
import { AwsRouter } from "./aws";
import { JWPlayerRouter } from "./jwPlayer";
import { RefundRouter } from "./refunds";
import { FcmTokensRouter } from "./fcmTokens";
import { InviteUserRouter, AcceptInviteRouter } from "./inviteUser";
import { ApiLogServices } from "../services/apiLog";
import { ErrorLogServices } from "../services/errorLog";
import { AutoCompleteRouter } from "./autoComplete";
import { SuperAdminRouter } from "./superAdmin";
import { ProductsRouter } from "./products";
import { OrderRouter } from "./orders";
import { UtilsRouter } from "./utils";
import { ReferralRouter } from "./referrals";
import { StripeSubscriptionRouter } from "./subscription";
import { NotificationsRouter } from "./notifications";
import { ProjectRouter } from "./projects";
import { PostRouter } from "./posts";
import { CommentRouter } from "./comments";
import { ProjectNotesRouter } from "./projectNotes";
import { ProjectTasksRouter } from "./projectTasks";
import { TagsRouter } from "./tags";
import { CompanyRouter } from "./company";
import { LikesRouter } from "./likes";
import { ReportsRouter } from "./reports";
import { ShortLinkRouter } from "./shortLink";
import { GalleryRouter } from "./gallery";
import { CheckListRouter } from "./checklist";
import { DailyLogRouter } from "./dailyLog";
import { SheetRouter } from "./sheet";
import { ProjectDocumentRouter } from "./projectDocuments";
import { AiProjectUpdateRouter } from "./aiProjectUpdate";
import { ProjectReportsRouter } from "./projectReport";
import { ApiKeyRouter } from "./apiKeys";
import { CrewsRouters } from "./crews";
import { BinRouter } from "./bin";
import { IntegrationRouter } from "./integrations";
import { WalkthroughRouter } from "./walkthrough";
import { OfflineRouter } from "./offline";
import { ErrorLogsRouter } from "./errorLogs";

const middleware = new Middleware();

export const api = express.Router();
api.use("/integrations", new IntegrationRouter().router);
api.use("/error-logs", new ErrorLogsRouter().router);

api.use(middleware.jwtDecoder);

api.use("/files", new FileRouter().router);
api.use("/admin", new AdminRouter().router);
api.use("/superAdmin", new SuperAdminRouter().router);
api.use("/auth", new AuthRouter().router);
api.use("/payment", new PaymentRouter().router);
api.use("/subscription", new StripeSubscriptionRouter().router);
api.use("/twilio", new TwilioRouter().router);
api.use("/email", new EmailRouter().router);
api.use("/chat", new ChatRouter().router);
api.use("/files", new FileRouter().router);
api.use("/review", new ReviewRouter().router);
api.use("/user", new UserRouter().router);
api.use("/aws", new AwsRouter().router);
api.use("/jw-player", new JWPlayerRouter().router);
api.use("/invite-users", new InviteUserRouter().router);
api.use("/accept-invite", new AcceptInviteRouter().router);
api.use("/refund", new RefundRouter().router);
api.use("/fcm-token", new FcmTokensRouter().router);
api.use("/autocomplete", new AutoCompleteRouter().router);
api.use("/products", new ProductsRouter().router);
api.use("/orders", new OrderRouter().router);
api.use("/utils", new UtilsRouter().router);
api.use("/referrals", new ReferralRouter().router);
api.use("/notification", new NotificationsRouter().router);
api.use("/projects", new ProjectRouter().router);
api.use("/posts", new PostRouter().router);
api.use("/comments", new CommentRouter().router);
api.use("/projectNotes", new ProjectNotesRouter().router);
api.use("/projectTasks", new ProjectTasksRouter().router);
api.use("/tags", new TagsRouter().router);
api.use("/company", new CompanyRouter().router);
api.use("/like", new LikesRouter().router);
api.use("/reports", new ReportsRouter().router);
api.use("/shortLink", new ShortLinkRouter().router);
api.use("/gallery", new GalleryRouter().router);
api.use("/checklist", new CheckListRouter().router);
api.use("/projectReports", new ProjectReportsRouter().router);
api.use("/dailyLogs", new DailyLogRouter().router);
api.use("/sheets", new SheetRouter().router);
api.use("/projectDocuments", new ProjectDocumentRouter().router);
api.use("/aiProjectUpdates", new AiProjectUpdateRouter().router);
api.use("/apiKeys", new ApiKeyRouter().router);
api.use("/crews", new CrewsRouters().router);
api.use("/bin", new BinRouter().router);
api.use("/walkthroughs", new WalkthroughRouter().router);
api.use("/offline", new OfflineRouter().router);

api.use(ApiLogServices.apiLog);
api.use(ErrorLogServices.errorLog);
